# Generated by Django 4.1.4 on 2023-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register_models",
            name="mobile",
            field=models.IntegerField(),
        ),
    ]
