# Generated by Django 4.1.4 on 2023-02-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce_app",
            "0003_attribute_category_product_specification_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute_value",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="image_product",
            name="image",
            field=models.FilePathField(
                path="/image/pro_<django.db.models.query_utils.DeferredAttribute object at 0x000001D67B4CE790>"
            ),
        ),
    ]
