# Generated by Django 4.1.4 on 2023-02-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0009_alter_image_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute_value",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="image_product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="ecommerce_app/media/image/pro_<django.db.models.query_utils.DeferredAttribute object at 0x0000028D17ACE790>",
            ),
        ),
    ]
