# Generated by Django 4.1.4 on 2023-02-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0009_alter_attribute_value_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute_value",
            name="price",
        ),
        migrations.RemoveField(
            model_name="attribute_value",
            name="quantity",
        ),
        migrations.AddField(
            model_name="attribute_product",
            name="name",
            field=models.CharField(default=" 55 ", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attribute_product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attribute_product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
