# Generated by Django 4.1.4 on 2023-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0010_alter_attribute_value_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image_product",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=60,
                upload_to="ecommerce_app/media/image/pro_<django.db.models.query_utils.DeferredAttribute object at 0x000002DCE256BD60>",
            ),
        ),
    ]
