# Generated by Django 4.1.4 on 2023-03-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0013_prand_tags_product_created_at_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
