# Generated by Django 4.1.4 on 2023-03-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0014_alter_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce_app.prand",
            ),
            preserve_default=False,
        ),
    ]
