# Generated by Django 4.1.4 on 2023-03-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0015_product_prand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag_product",
            old_name="Product",
            new_name="product",
        ),
    ]
