# Generated by Django 4.1.4 on 2023-03-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0013_slider"),
        ("ecommerce_app", "0017_rename_tag_tags_name"),
    ]

    operations = []
