# Generated by Django 4.1.4 on 2023-03-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0014_order_alter_slider_image_shippingaddress_orderitem"),
        ("ecommerce_app", "0018_merge_0013_slider_0017_rename_tag_tags_name"),
    ]

    operations = []
