# Generated by Django 4.1.4 on 2023-03-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0019_merge_20230304_1523"),
        ("ecommerce_app", "0020_alter_order_transaction_id"),
    ]

    operations = []
