# Generated by Django 4.1.4 on 2023-03-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0020_contact_register_models_address_review"),
        ("ecommerce_app", "0021_merge_20230307_2258"),
    ]

    operations = []
