# Generated by Django 4.1.4 on 2023-03-08 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0023_featuredproducut"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredproducut",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 8, 13, 27, 7, 85309, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
