# Generated by Django 4.1.4 on 2023-03-08 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0024_featuredproducut_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredproducut",
            name="due_date",
        ),
        migrations.AddField(
            model_name="featuredproducut",
            name="experation_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 8, 13, 30, 0, 570313, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
