# Generated by Django 4.1.4 on 2023-03-08 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0028_alter_featuredproducut_experation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredproducut",
            name="experation_date",
        ),
        migrations.AddField(
            model_name="featuredproducut",
            name="experation_date_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 10, 11, 39, 17, 694570, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
