# Generated by Django 4.1.4 on 2023-03-08 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0029_remove_featuredproducut_experation_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredproducut",
            name="experation_date_at",
        ),
        migrations.AddField(
            model_name="featuredproducut",
            name="xpiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 10, 11, 41, 0, 267085, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
