# Generated by Django 4.1.4 on 2023-03-08 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0030_remove_featuredproducut_experation_date_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredproducut",
            name="xpiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 10, 14, 24, 18, 88916, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
