# Generated by Django 4.1.4 on 2023-03-09 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0031_alter_featuredproducut_xpiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredproducut",
            name="xpiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 11, 10, 5, 41, 182117, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Category_Side",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("active", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, upload_to="image/cat")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app.category",
                    ),
                ),
            ],
        ),
    ]
