# Generated by Django 4.1.4 on 2023-03-09 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0032_alter_featuredproducut_xpiration_time_category_side"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vertical_Side",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("sub_title", models.CharField(max_length=100)),
                ("link", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Size: 250x200", upload_to="image/Vertical_slider"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="category_side",
            name="title",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="featuredproducut",
            name="xpiration_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 11, 11, 37, 35, 855373, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
